### ISSUE TITLE
[bug]无法备份存档

### ISSUE THREAD

**Issue by syf097** [HowyoungZhou/MinecraftSavesBackup#1]
3月1日跟新到最新版后无法备份存档，每次备份都是0mb大小，在重新设置时弹出如下错误：
![1](https://cloud.githubusercontent.com/assets/9026136/6442379/430fd682-c12a-11e4-8241-3de186aabea2.gif)
估计与压缩有关
另外更改完设置后再点更改无反应

**Comment by zhou-haoyang** [comment]
您是通过自动更新更新的吗？如果是，这是一个已知问题，请手动卸载原程序并[下载](http://sourceforge.net/projects/minecraftsavesbackup/files/Release/minecraftsavesbackup_setup.exe/download)最新版本的程序安装即可解决。更改完设置后再点更改无反应的问题我已经发现了，正在解决当中。

**Comment by zhou-haoyang** [comment]
5月22日推送的1.1.0.8版本([下载](http://sourceforge.net/projects/minecraftsavesbackup/files/Release/minecraftsavesbackup_setup.exe/download))解决了这一问题。
